### PR TITLE
Make simulation code more user friendly

### PR DESCRIPTION
**Pull request by samueljackson92**
I've done a fair bit of work in the past couple of days to tidy up the code for this. Some significant changes are:
 - A documentation page!
 - A command line interface
 - Use of a separate config file instead of hard coded parameters
 - Better code structure
 - Fixed several issues preventing the script being run via the command line.
 - Fixed a bug where we could potentially miss peaks on the edge of the instrument's visible Q space.

### CODE REVIEW

**Comment by Anders-Markvardsen** [comment]
Hi, tests so far on autoreduce:

`python scd-sim mask -i ../../../peaks-share/masks/SXD23767.raw -o sxdmask -c my_config.json`

my_config.json is a copy of the default config. This produces the output sxdmask.npy. Then I try:

`python scd-sim create -i ../../../peaks-share/cifs/SrO.cif -o ./simulation -m sxdmask.npy -c my_config.json`

This produces the 

> AddPeakHKL-[Notice] AddPeakHKL successful, Duration 0.00 seconds
AddPeakHKL-[Notice] AddPeakHKL started
AddPeakHKL-[Notice] AddPeakHKL successful, Duration 0.00 seconds
AddPeakHKL-[Notice] AddPeakHKL started
AddPeakHKL-[Notice] AddPeakHKL successful, Duration 0.00 seconds
AddPeakHKL-[Notice] AddPeakHKL started
AddPeakHKL-[Notice] AddPeakHKL successful, Duration 0.00 seconds
CreateMDWorkspace-[Notice] CreateMDWorkspace started
CreateMDWorkspace-[Notice] CreateMDWorkspace successful, Duration 0.00 seconds
BinMD-[Notice] BinMD started
BinMD-[Notice] BinMD successful, Duration 0.65 seconds
DeleteWorkspace-[Notice] DeleteWorkspace started
DeleteWorkspace-[Notice] DeleteWorkspace successful, Duration 0.00 seconds
SaveMD-[Notice] SaveMD started
SaveMD-[Error] Error in execution of algorithm SaveMD:
SaveMD-[Error] NXopen(simulation/simulation/SXD_0_MD.nxs, 5) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/anders_git_checkout/ml_peak_finding/src/scd-sim/__main__.py", line 91, in <module>
    make_data(args, config)
  File "/anders_git_checkout/ml_peak_finding/src/scd-sim/__main__.py", line 63, in make_data
    args.prefix, args.output_dir)
  File "scd-sim/simulate.py", line 41, in create_simulated_data
    api.SaveMD(ws, file_prefix+"_MD.nxs")
  File "/opt/Mantid/bin/mantid/simpleapi.py", line 926, in algorithm_wrapper
    algm.execute()
RuntimeError: NXopen(simulation/simulation/SXD_0_MD.nxs, 5) failed
root@c71604cc0d3f:/anders_git_checkout/ml_peak_finding/src# python scd-sim create -i ../../../peaks-share/cifs/SrO.cif -o ./simulation -m sxdmask.npy -c my_config.json python scd-sim create -i ../../../peaks-share/cifs/SrO.cif -o ./simulation -m sxdmask.npy -c my_config.json
FrameworkManager-[Notice] Welcome to Mantid 3.9.2
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid3.9.2
CheckMantidVersion-[Notice] A new version of Mantid(3.10.0) is available for download from http://download.mantidproject.org
usage: scd-sim [-h] {create,mask} ...
scd-sim: error: unrecognized arguments: python scd-sim create

> ********* SEGMENTATION FAULT *********
 /opt/Mantid/lib/libMantidAPI.so(+0x154f96) [0x7f4cf02c8f96]
 /opt/Mantid/lib/libMantidAPI.so(+0x1550af) [0x7f4cf02c90af]
 /lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x7f4d02f52cb0]
 /opt/Mantid/lib/libMantidKernel.so(_ZN6Mantid6Kernel6Logger3logERKSsN4Poco7Message8PriorityE+0x10) [0x7f4cfe7aaa80]
 /opt/Mantid/plugins//libMantidDataHandling.so(_ZN6Mantid12DataHandling18DownloadInstrument4execEv+0x71d) [0x7f4cef3ec66d]
 /opt/Mantid/lib/libMantidAPI.so(_ZN6Mantid3API9Algorithm7executeEv+0x410) [0x7f4cf024bf70]
 /opt/Mantid/lib/libMantidAPI.so(_ZN6Mantid3API9Algorithm16executeAsyncImplERKN4Poco4VoidE+0x14) [0x7f4cf0243cc4]
 /opt/Mantid/lib/libMantidAPI.so(_ZN6Mantid3API14AlgorithmProxy16executeAsyncImplERKN4Poco4VoidE+0x1f) [0x7f4cf0266d3f]
 /opt/Mantid/lib/libMantidAPI.so(+0xf3d39) [0x7f4cf0267d39]
 /usr/lib/libPocoFoundation.so.31(_ZN4Poco12PooledThread3runEv+0x97) [0x7f4cfdb49f27]
 /usr/lib/libPocoFoundation.so.31(_ZN4Poco10ThreadImpl13runnableEntryEPv+0x86) [0x7f4cfdb45fa6]
 /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f4d032ec184]
 /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f4d03019bed]

@samueljackson92 is I doing anything obviously wrong?

**Comment by Anders-Markvardsen** [comment]
Probably not that important but observed that if I try to run scd-sim through mantidpython using 
‘run scd-sim  mask –i etc…’ this is not working. Reading: https://stackoverflow.com/questions/9636617/running-module-from-ipython-interpreter-instead-of-command-line there might seem to be some limitation with running __main__.py from ipython.

**Comment by samueljackson92** [comment]
@Anders-Markvardsen Not sure. At a guess I would say mantidpython cannot be passed command line arguments. Have you tried running the command from with an interactive session of mantidpython e.g. something like:
```bash
bash$ mantidpython
>>> %run scd-sim create ...
```

**Comment by Anders-Markvardsen** [comment]
Just tried with '%run' instead of 'run' and get same response

**Comment by samueljackson92** [comment]
Try executing it from within the interactive `mantidpython` terminal but add the `-m` flag immediately after the `%run`. This should tell python to run the module. The full command for me was:
```
 %run -m scd-sim create -i ../../peaks-share/cifs/SrO.cif -o ../../peaks-share/simulated_data/ -c config.example.json -m sxdmask.npy
```

**Comment by Anders-Markvardsen** [comment]
-m helped somewhat - although generate other error now also with mask command - easier if I show you off line

**Comment by MikeHart85** [comment]
Following up on our discussions regarding `LoadInstrument` in Mantid, and allowing it to accept `IMDWorkspace`s instead of `MatrixWorkspace`s:

It doesn't look like it will be as trivial to make this change as we though, and perhaps we don't even want to. 

The problem is that `Workspace` and `IMDWorkspace` don't appear to know anything about an Instrument. Even `MatrixWorkspace` only knows about it because it inherits `ExperimentInfo`.

Apart from `m_workspace->setInstrument()`, the `LoadInstrument` algorithm also calls `populateInstrumentParameters()` and `getWorkspaceStartData()`. All three of these are members of `ExperimentInfo` (inherited by `MatrixWorkspace`). It also calls `rebuildSpectraMapping()`, which is a member of `MatrixWorkspace`.

Is there any reason we can't use `MatrixWorkspace`?

**Comment by samueljackson92** [comment]
@MikeHart85 I've added a new issue (#5) to address your comments.

**Comment by Anders-Markvardsen** [comment]
I am happy. @MikeHart85 I will merge in but please reopen if like further changes to this pull request

**Pull request closed without merging**
